import subprocess
import os
import webbrowser
import json

def execute_action(action: dict) -> str:
    try:
        if action["type"] == "launch":
            subprocess.Popen(action["args"], cwd=action.get("cwd"))
            return f"Launched: {action['label']}"

        if action["type"] == "web":
            webbrowser.open(action["url"])
            return f"Opened: {action['url']}"

        if action["type"] == "code":
            with open(action["path"], "w") as f:
                f.write(action["content"])
            subprocess.Popen(["python", action["path"]], cwd=os.path.dirname(action["path"]))
            return f"Executed code: {action['path']}"

        return "Unknown action type."
    except Exception as e:
        return f"[Execution error] {str(e)}"

def route_command(text: str) -> dict:
    # Placeholder for semantic routing — replace with model or vector search
    if "open photoshop" in text.lower():
        return { "type": "launch", "args": ["C:\\Program Files\\Adobe\\Adobe Photoshop 2023\\Photoshop.exe"], "label": "Photoshop" }

    if "search google for" in text.lower():
        term = text.lower().split("search google for")[-1].strip()
        return { "type": "web", "url": f"https://www.google.com/search?q={term}" }

    if "write python code" in text.lower():
        return {
            "type": "code",
            "path": "D:\\sapience\\scripts\\generated.py",
            "content": "# Generated by Sapience\nprint('Hello from Sapience')"
        }

    return { "type": "unknown" }